export const siteConfigs = {
  title: 'The Logos Blog',
  heroTitle: ['The Logos Blog'],
  description:
    'Your Guide to Network States and the Technology Driving Sovereign Communities',
  keywords: [
    'book club',
    'censorship resistance',
    'citizens',
    'finance',
    'network state',
    'op ed',
    'panarchy',
    'pr',
    'privacy',
    'security',
    'show',
    'technology',
    'update',
    'whistleblower',
  ],
  url: 'https://blog.logos.co',
  xHandle: 'logos_network',
  youtubeHandle: '@LogosNetwork',
  githubHandle: 'logos-co',
}
